org.gradle.jvmargs=-Xmx4G -DProxyHost=127.0.0.1 -DProxyPort=1082

#Build variables
modVersion=4.22-2.0-3
modName=LibrarianLib-Continuous
modGroup=com.teamwizardry.librarianlib
corePlugin=com.teamwizardry.librarianlib.asm.LibLibCorePlugin

#Build settings
org.gradle.caching=true
org.gradle.parallel=true
